from setuptools import setup, find_packages

setup(
    name='mikey',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'openai',
        'PyQt6',
        'SpeechRecognition',
        'FasterWhisper',
        'vosk',
        'openwakeword',
        'porcupine-api',
        'pyttsx3',
        'piper-tts',
        'PyAutoGUI',
        'keyboard',
        'mouse',
        'psutil',
        'watchdog',
        'playwright',
        'selenium',
        'pycaw',
        'pygetwindow',
        'chromadb',
        'faiss-cpu',
        'psutil',
        'pytesseract',
        'Pillow',
        'fastapi',
        'uvicorn',
        'python-multipart',
        'python-dotenv',
    ],
    entry_points={
        'console_scripts': [
            'mikey=mikey.main:main',
        ],
    },
    author='Manus AI',
    description='An advanced autonomous AI desktop assistant inspired by JARVIS.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/khatririshi/FoodieExpress/mikey',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.9',
)
